
executable              = $(directory)/batchScript.sh
arguments               = /afs/cern.ch/user/g/gmarozzo/CMSSW_12_6_4/src/test/Dir/$(directory) $(ClusterId)$(ProcId)
output                  = log/$(ClusterId).$(ProcId).out
error                   = log/$(ClusterId).$(ProcId).err
log                     = log/$(ClusterId).log
Initialdir              = $(directory)
request_memory          = 4000M
#Possible values: https://batchdocs.web.cern.ch/local/submit.html
+JobFlavour             = "workday"

x509userproxy           = /afs/cern.ch/user/g/gmarozzo/x509up_u136841

#https://www-auth.cs.wisc.edu/lists/htcondor-users/2010-September/msg00009.shtml
periodic_remove         = JobStatus == 5

#ShouldTransferFiles     = NO

transfer_input_files = ../../../CTPPSTimeCalibration/ppsALL.sqlite